import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function AlertDeliveriesPage() {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return (
      <div className="mx-auto max-w-4xl space-y-6">
        <h1 className="text-3xl font-bold text-white">
          Alert Deliveries
        </h1>

        <p className="text-slate-400">
          Sign in to view your alert deliveries.
        </p>

        <Link
          href="/account/login"
          className="text-sky-400 hover:underline"
        >
          Sign in →
        </Link>
      </div>
    );
  }

  const { data: alerts } = await supabase
    .from("user_alerts")
    .select("id")
    .eq("user_id", user.id);

  const alertIds = (alerts || []).map(
    (alert) => alert.id,
  );

  const { data: deliveries } =
    alertIds.length > 0
      ? await supabase
          .from("alert_delivery_queue")
          .select(
            "id, alert_id, change_id, delivery_type, status, title, message, queued_at, processed_at, error_message",
          )
          .in("alert_id", alertIds)
          .order("queued_at", {
            ascending: false,
          })
          .limit(100)
      : { data: [] };

  return (
    <div className="mx-auto w-full max-w-6xl space-y-8">
      <header className="space-y-3">
        <p className="text-sm font-bold uppercase tracking-[0.18em] text-sky-400">
          Intelligence
        </p>

        <h1 className="text-4xl font-bold text-white">
          Alert Deliveries
        </h1>

        <p className="text-slate-400">
          Notifications generated by your intelligence alerts.
        </p>
      </header>

      <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
        {!deliveries?.length ? (
          <p className="text-sm text-slate-400">
            No alert deliveries have been generated yet.
          </p>
        ) : (
          <div className="space-y-4">
            {deliveries.map((delivery) => (
              <article
                key={delivery.id}
                className="rounded-xl border border-slate-800 bg-slate-950 p-5"
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <h2 className="font-semibold text-white">
                      {delivery.title ||
                        "Intelligence alert"}
                    </h2>

                    <p className="mt-2 text-sm leading-6 text-slate-400">
                      {delivery.message}
                    </p>
                  </div>

                  <span className="rounded-full border border-slate-700 px-3 py-1 text-xs font-semibold text-slate-300">
                    {delivery.status}
                  </span>
                </div>

                <div className="mt-4 flex flex-wrap gap-4 text-xs text-slate-500">
                  <span>
                    Delivery: {delivery.delivery_type}
                  </span>

                  {delivery.change_id && (
                    <Link
                      href={`/changes?change=${delivery.change_id}`}
                      className="text-sky-400 hover:underline"
                    >
                      View change
                    </Link>
                  )}

                  <span>
                    {new Date(
                      delivery.queued_at,
                    ).toLocaleString()}
                  </span>
                </div>
              </article>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}